// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215202200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Data.Entities.ComputerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfProduction")
                        .HasColumnType("TEXT")
                        .HasColumnName("production_date");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpu = "Intel i5-12400",
                            DateOfProduction = new DateOnly(2022, 5, 10),
                            Gpu = "NVIDIA GTX 1660",
                            Name = "Dell Inspiron",
                            Producent = "Dell",
                            Ram = "16GB DDR4"
                        },
                        new
                        {
                            Id = 2,
                            Cpu = "AMD Ryzen 7 5800U",
                            DateOfProduction = new DateOnly(2021, 11, 20),
                            Gpu = "Integrated Radeon",
                            Name = "Lenovo ThinkPad",
                            Producent = "Lenovo",
                            Ram = "32GB DDR4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
